services:
  postgres_db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-bank}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 3

  app:
    build: .
    volumes:
      - .:/app
      - ./migrations:/app/migrations
    environment:
      DB_HOST: postgres_db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-bank}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}

    ports:
      - "8000:8000"
    depends_on:
      postgres_db:
        condition: service_healthy
    command: >
      sh -c "while ! pg_isready -h postgres_db -U ${DB_USER:-posgres}; do sleep2; done &&
            cd /app &&
            alembic upgrade head &&
            cd .. &&
            uvicorn main:app --host 0.0.0.0 --port 8000"

volumes:
  postgres_data:
