"""Initial

Revision ID: 5e97b4d574ab
Revises: 
Create Date: 2025-07-31 10:26:04.200642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e97b4d574ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.CheckConstraint('balance >=0'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('operation_type', sa.Enum('deposit', 'withdraw', name='operationtype'), nullable=False),
    sa.Column('time', sa.DateTime(), server_default=sa.text("TIMEZONE( 'utc', now())"), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_account_id'), 'history', ['account_id'], unique=False)
    op.create_index(op.f('ix_history_operation_type'), 'history', ['operation_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_history_operation_type'), table_name='history')
    op.drop_index(op.f('ix_history_account_id'), table_name='history')
    op.drop_table('history')
    op.drop_table('accounts')
    # ### end Alembic commands ###
