"""empty message

Revision ID: 7501c163df95
Revises: 5e97b4d574ab
Create Date: 2025-07-31 17:14:08.832917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7501c163df95'
down_revision: Union[str, Sequence[str], None] = '5e97b4d574ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('amount', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'amount')
    # ### end Alembic commands ###
